# Generated by Django 5.1 on 2024-08-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_users_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
